### ISSUE TITLE
NodeJS Google Drive Documentation

### ISSUE THREAD

**Issue by zhiyanxie** [googleapis/google-api-nodejs-client#1356]
Hi Team,  there is not much Google Drive Documentation for the Google Drive but only samples with limited features. Could you please provide more detail for the API?

For example, I tried to upload a html to google drive, and I want it transformed to Google Docs,  I can do it from Client Side Restful API with  'params': {'uploadType': 'multipart', 'convert': 'true'}, But in nodejs, There is so much transforming process, like merging options. So it is a little difficult to understand from the source code, because all the property name are different in nodejs:

```js
  drive.files.create(
    {
      resource: metadata,
      requestBody: {
      },
      media: {
        mimeType: 'text/html',
        body: doc
      },
```

So what should I pass to transform html to google docs?

Thank you very much!

**Comment by grant** [comment]
I cannot tell what the specific question in this issue is.
- Google Drive files creation: [Examples](https://developers.google.com/drive/api/v3/manage-uploads)
- Transform HTML to Google Docs: The Google Docs API is not generally available, but you can request access [here](https://developers.google.com/docs/).
