### ISSUE TITLE
Support for Gsuite marketplace api

### ISSUE THREAD

**Issue by angrykoala** [googleapis/google-api-nodejs-client#1593]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
There doesn't appear to be a way (or I couldn't find docs related) to use googleapis to connect to Gsuite marketplace license APIs (https://www.googleapis.com/appsmarket/v2/licenseNotification/). 

 **Describe the solution you'd like**
Would it be possible perform requests to this service using the nodejs client?
 **Describe alternatives you've considered**
I can only think of performing a raw http request to the API.

**Comment by grant** [comment]
@JustinBeckwith 

Looks like this a public non-discoverable API.

I've tried:

```
npm run generate --discovery-url "https://www.googleapis.com/discovery/v1/apis/appsmarket/v2/rest"
```

but the command only produced a `src/apis/appsmarket/v2.ts` without the other files (`package.json`, etc.)

Any tips?

**Comment by JustinBeckwith** [comment]
That isn't a path that's super well tested.  At a glance - it looks like we need to make a fix to actually generate those files if producing a single lib.

Alternatively - should we just reach out to the appsmarket team and ask them why they aren't available in the public index?

**Comment by grant** [comment]
For the generation part, there's probably another way I'm missing.
I've asked the team about the public index part.

**Comment by JustinBeckwith** [comment]
Sadly - there's not a lot we can do with this if the API isn't added to the discovery index we use to generate this library.  Just so you can follow along - please file an issue here:
https://issuetracker.google.com/issues/new?component=191597&template=823911

Feel free to link to this issue, and ask them to add the API to the discovery index :) As soon as it's available there - it would be automatically included in this library.  It would be super awesome if you would link back to that issue here.  Hope this helps!

**Comment by shlasouski** [comment]
Google issue: https://issuetracker.google.com/issues/184060950
