### ISSUE TITLE
Typescript and drive.file.exports

### ISSUE THREAD

**Issue by mlecoq** [googleapis/google-api-nodejs-client#1683]
#### Environment details

  - OS: Mojave
  - Node.js version: 10.13.0
  - npm version: 6.4.1
  - `googleapis` version: 39.2.0

#### Steps to reproduce

When I export a csv file with the following code 

```
 const result = await drive.files.export({
    fileId,
    mimeType: "text/csv"
  });

  console.log(result.data);

  console.log(typeof result.data);
```

I have the follow result 

```
key,fr,en
hello,Bonjour,Good Morning
string
```

So I get back a string. 

But the returned type of export method is _GaxiosResponse<void>_ so data type is void according to method signature. 

Could it be possible to change the returned type ?
```
 export<T>(params?: Params$Resource$Files$Export, options?: MethodOptions): GaxiosPromise<T>;
```

or am I missing something ?

**Comment by JustinBeckwith** [comment]
Thanks for reporting this!  All of the types for this library are automatically generated, based on the discovery doc found here:
https://www.googleapis.com/discovery/v1/apis/drive/v3/rest

If you search for `drive.files.export`, you can see there's no `response` element that would let us know what type of data is returned.  I would expect to find something like this:

```
"response": {
  "$ref": "File"
 },
```

Sadly - this is a bug with the underlying discovery doc, and not the generator.  Just so you can follow along - would you mind being the one to file the issue in their issue tracker?
https://issuetracker.google.com/issues/new?component=191650&template=823909

I would copy most of the message here (they'll know what it means).  That way you can get notifications as it's fixed :) . Since there's not a lot we can do with this one - I'm going to close it out.  As soon as the underlying bug is fixed in the API, this lib will pick up the changes automagically :)

**Comment by aendrew** [comment]
As a work-around in the meantime, this will type the response correct, assuming `doc.data` is a `string` type:

```typescript
        const doc = await ((drive.files.export({
            fileId: key,
            auth: client,
            mimeType: "text/plain"
        }) as unknown) as GaxiosPromise<string>);
```

You need to cast it as "unknown" first and then to a `GaxiosPromise<string>` (replace "string" with whatever type you expect the response to be)
