### ISSUE TITLE
BCC not received from email

### ISSUE THREAD

**Issue by munkhorgil** [googleapis/google-api-nodejs-client#1779]
I want to reply to email with bcc, but I cannot get bcc from api header like cc, to etc.
How can I reply to BCC using gmail API?

**Comment by JustinBeckwith** [comment]
Greetings!  Are you trying to:
- Send an email with someone 'bcc'd 
- Figure out who was on the 'bcc' line of an email you receive

If you're trying to send an email with a bcc line - check out this samples!
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/gmail/send.js#L31

Otherwise - you shouldn't be able to see who was on the bcc of an email you receive :) Can you share any details on which of these you're trying to do?

**Comment by munkhorgil** [comment]
Thanks @JustinBeckwith, I am not able to see who was on the bcc of a received email was the point

**Comment by gmwill934** [comment]
How do I actually see the BCC recipient(s)? I'm using Node JS and I cannot see it, I only see "`to`", "`from`" and "`cc`".
In case someone sends an email like this. I'd like the BCC header to be displayed so I can reply back

Take the following example 

```
from: team@google.com
to: cloud@google.com
cc: hr@google.com
bcc: myOwnPersonalEmail@gmail.com
```

Thanks

**Comment by billzagoras** [comment]
> How do I actually see the BCC recipient(s)? I'm using Node JS and I cannot see it, I only see "`to`", "`from`" and "`cc`". In case someone sends an email like this. I'd like the BCC header to be displayed so I can reply back
> 
> Take the following example
> 
> ```
> from: team@google.com
> to: cloud@google.com
> cc: hr@google.com
> bcc: myOwnPersonalEmail@gmail.com
> ```
> 
> Thanks

Hello all! Is this one resolved? I am having the same issue when accessing the gmail api from golang. I cannot see any bcc headers even though there are bccs added to the original email.
