### ISSUE TITLE
Cannot assign to read only property 'token_type'

### ISSUE THREAD

**Issue by vmasek** [googleapis/google-api-nodejs-client#1831]
#### Environment details

I'm trying to get this SDK work in Angular 8 + CLI (Webpack) build,

  - OS: `Fedora 30`
  - Node.js version: `v10.16.3`
  - npm version: `6.9.0`
  - `googleapis` version: `^43.0.0`

#### Steps to reproduce

Problem is when I try to get Calendar event using the OAuth2

```
          const calendar = google.calendar({
            version: 'v3',
            auth: this.oauth2Client,
          });

          calendar.events
            .list({ calendarId: CALENDAR_ID_EVENTS })
            .then(res => console.log(res))
            .catch(e => console.error(e));
```

Actual error is: 
`TypeError: Cannot assign to read only property 'token_type' of object '[object Object]'`
`at OAuth2Client.getRequestMetadataAsync (oauth2client.js:252)`

if I get rid of this assignment on that very line everything works as intended
`thisCreds.token_type = thisCreds.token_type || 'Bearer';`

**Comment by bcoe** [comment]
@vmasek I believe the issue is that you're passing an object into credentials that is immutable, similar to this bug on stack overflow:

https://stackoverflow.com/questions/55587708/cannot-assign-to-read-only-property-closed-of-object-object-object

Is there a chance that `this.oauth2Client` is stored in a way similar to what is described in the issue above; if so, could you make it a plain-old-JavaScript-object?

**Comment by vmasek** [comment]
Thank you @bcoe, I've solved it by 
`this.oauth2Client.setCredentials({ ...tokens });` 
instead of 
`this.oauth2Client.setCredentials(tokens);`

**Comment by vmasek** [comment]
Was it caused by `OAuth2Client.getToken` returning frozen/immutable object?
