### ISSUE TITLE
Is it possible to create a new sheet and append values to it using a single call to sheets.spreadsheets.batchUpdate()?

### ISSUE THREAD

**Issue by sashaskull** [googleapis/google-api-nodejs-client#1925]
Hi!

Up until now I have been calling sheets.spreadsheets.batchUpdate() and then sheets.spreadsheets.values.append() in order to put values on the newly created sheet. I was wondering if I could insert a second request within the "requests: []" when calling the batchUpdate since it can hold more than one request at I time, in order to append the values right after creating the new sheet without having to make an additional api call of sheets.spreadsheets.values.append() to be able to put values in it.

I have been fiddling around and I feel I am close enough, but got to the following:

```
"requests": [
          {
            "addSheet": {
              "properties": {
                "title": "Prueba",
                "sheetId": 9
              }
            }
          },
          {
            "appendCells": {
              "rows": [
                {
                  "values": [
                    {
                      "userEnteredValue": {
                        "stringValue": "Work"
                      }
                    }
                  ]
                }
              ],
              "fields": "userEnteredValue",
              "sheetId": 9
            }
          }
        ]
```

The problem here is that since "sheetId" will be unknown until the sheet gets created and given a sheetId value, I am force to give myself an id for the appendCells to be able to find the sheet I just created. Is there any documentation/idea on how to achieve this without having to manually specify the sheetId myself?

**Comment by fhinkel** [comment]
Hi @sashaskull , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Sheets APII tag](https://stackoverflow.com/questions/tagged/google-sheets-api) is most appropriate for design and general troubleshooting.
* [Google Sheets API's public issue tracker](https://developers.google.com/sheets/api/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Comment by sashaskull** [comment]
Hi @fhinkel !

Thanks for letting me know about this, I have decided to post this question on [Stackoverflow](https://stackoverflow.com/questions/65185286/is-it-possible-to-create-a-new-sheet-and-append-values-to-it-using-a-single-call) as you suggested!

**Comment by fhinkel** [comment]
Great, thank you.
