### ISSUE TITLE
Docs API replace text with image

### ISSUE THREAD

**Issue by iaarab** [googleapis/google-api-nodejs-client#1927]
Replacing text with text is straight forward and well documenten.
But how do we change text with an image? it seems like you can only change image with a image.

This is necessary for adding images at a specific position in the document.

**Comment by fhinkel** [comment]
Hi @iaarab , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Docs API tag](https://stackoverflow.com/questions/tagged/google-docs-api) is most appropriate for design and general troubleshooting.
* [Google Docs API's public issue tracker](https://developers.google.com/docs/api/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
