### ISSUE TITLE
file.createReadStream writes 0 bytes when passed directly

### ISSUE THREAD

**Issue by sseppola** [googleapis/google-api-nodejs-client#2015]
#### Environment details

  - OS: Firebase Functions
  - Node.js version: 8
  - npm version: 
  - google-cloud-node version:
	"@google-cloud/storage": "3.3.1",
	"googleapis": "^43.0.0",

#### Steps to reproduce
I have a firebase function that copies a file from GCS to Google Drive, and I had a weird issue.

I made a small lib for myself to handle the GDrive interaction (TypeScript):
```ts
import stream = require('stream');
import { google } from 'googleapis';

async function getGoogleAuth() {
  // This method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS environment variables.
  const auth = new google.auth.GoogleAuth({
    // Scopes can be specified either as an array or as a single, space-delimited string.
    scopes: ['https://www.googleapis.com/auth/drive'],
  });

  const [authClient, projectId] = await Promise.all([
    auth.getClient(),
    auth.getProjectId(),
  ]);

  return authClient;
}

export async function uploadFileToGDrive(
  fileStream: stream.Readable,
  opts: {
    name: string;
    parents: string[]; // parent directories
    mimeType: string;
  }
) {
  const auth = await getGoogleAuth();
  const drive = google.drive({ version: 'v3', auth });

  const fileMetadata = {
    name: opts.name,
    parents: opts.parents,
  };

  const media = {
    mimeType: opts.mimeType,
    body: fileStream,
  };

  const file = await drive.files.create({
    // @ts-ignore
    resource: fileMetadata,
    media: media,
    fields: 'id, name, mimeType, driveId',
  });

  return file;
}
```

My Firebase Function basically does the following:
```js
const bucketName = 'todo';
export const storageWatcher = functions
  .region('europe-west1')
  .storage.bucket(bucketName)
  .object()
  .onFinalize(async object => {
	const file = storage.bucket(bucketName).file(object.name)
	const fileStream = file.createReadStream();
	
	await uploadFileToGDrive(fileStream, {
        name: object.name,
        mimeType: object.contentType,
        parents: ['shared_dir_in_g_drive'],
      })
```
However that creates the file with the correct name, but the file is 0 bytes.. 
The fix is to pipe the file read stream through `stream.PassThrough` instead of using the readStream directly, to the code becomes:

```js
const file = storage.bucket(bucketName).file(object.name)
const fileStream = file.createReadStream();

const dataStream = new stream.PassThrough();
fileStream.pipe(dataStream);
	
await uploadFileToGDrive(dataStream, {
   name: object.name,
   mimeType: object.contentType,
   parents: ['shared_dir_in_g_drive'],
})
```
This works like a charm.. but I don't know why.

I'll admit my stream knowledge is limited, but I expected the PassThrough to be unnecessary in this scenario.

**Comment by fhinkel** [comment]
Hi @sseppola , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Drive API tag](https://stackoverflow.com/questions/tagged/google-drive-api?tab=Newest) is most appropriate for general troubleshooting.
* [Google Drive API's public issue tracker](https://developers.google.com/drive/api/v3/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
