### ISSUE TITLE
Google Drive - Single-parent model & path based addressing

### ISSUE THREAD

**Issue by sudhakar3697** [googleapis/google-api-nodejs-client#2050]
Hi,

I would like to know what would happen to the file(s)/folder(s) which already got multiple parents.

Any plan of supporting paths for addressing a file/folder (With ancestor info)?.
Something like **_\My Drive\abc\def\xyz.docx_**

Thank you :).

**Comment by JustinBeckwith** [comment]
Greetings!  Is this a question specifically about the `googleapis` npm module, or about the Drive API itself?  Are you able to get the information you need from the API here?
https://developers.google.com/drive/api/v3/reference/files/list

**Comment by sudhakar3697** [comment]
@JustinBeckwith  I am extremely sorry for the delay in response.

My question is about the Drive API itself.

Q1. Currently, files/folder can have multiple parents. 
[Beginning Sept. 30, 2020, you will no longer be able to place a file in multiple parent folders; every file must have exactly one parent folder location.](https://developers.google.com/drive/api/v3/ref-single-parent).
 I would like to know what would happen to the file(s)/folder(s) which already got multiple parents.

Q2. Currently, files/folders are identified by Id. Any plan of supporting paths for addressing a file/folder (With ancestor info)?.
Something like \My Drive\abc\def\xyz.docx

Thank you.

**Comment by sudhakar3697** [comment]
@JustinBeckwith Kindly remove the 'needs more info' label if further info isn't required.
Thank you.

**Comment by fhinkel** [comment]
Hi @sudhakar3697 , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Drive API tag](https://stackoverflow.com/questions/tagged/google-drive-api?tab=Newest) is most appropriate for general troubleshooting.
* [Google Drive API's public issue tracker](https://developers.google.com/drive/api/v3/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
