### ISSUE TITLE
Typescript interface should only be null when necessary

### ISSUE THREAD

**Issue by Sytten** [googleapis/google-api-nodejs-client#2232]
**Is your feature request related to a problem? Please describe.**
Currently all the generated types are nullable. This is very annoying when you use strict null check. Many (probably the majority) of those fields are not nullable anyway and it would greatly improve the productivity/correctness if they would be marked as such.

 **Describe the solution you'd like**
It would make a world of difference if we could know which field are really nullable and which ones are not without reading the document.

 **Describe alternatives you've considered**
You can force a not null with `!`.

**Comment by JustinBeckwith** [comment]
Greetings!  Sadly, not much I can do about this one :/  We had to add `null` as a possible value over here:
https://github.com/googleapis/google-api-nodejs-client/pull/1824

In response to this bug here:
https://github.com/googleapis/google-api-nodejs-client/issues/1559

The root of the problem is a lack of expressiveness of the discovery documents we use.  See this example:
https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest

There are properties in these schemas where "unset" is different from "null", and each have different semantic meaning.  The idea of "nullable" isn't expressed in the schema we use to generate the API, so we need to assume that all of the fields are nullable. 

Apologies!
