### ISSUE TITLE
"maximum redirect reached" error when Google serves a captcha page

### ISSUE THREAD

**Issue by bradvogel** [googleapis/google-api-nodejs-client#2251]
This is mostly an open question for anyone else who might be seeing this.

Sometimes when making a call to any Google Calendar API using this library, it's throwing the exception:

```
maximum redirect reached at: https://www.googleapis.com/calendar/v3/users/me/settings/autoAddHangouts?prettyPrint=false&google_abuse=GOOGLE_ABUSE_EXEMPTION%3DID%3D12ebfa30f602578e:TM%3D1592517701:C%3D%3E:IP%3D52.21.209.42-:S%3DAPGng0uPILcC3D-864_OoBE0ADNOMNgOnA%3B+path%3D/%3B+domain%3Dgoogle.com%3B+expires%3DFri
```

Unfortunately I can't share code that reproduces this 100%, as it happens only very intermittently. However, based on the presence of `GOOGLE_ABUSE_EXEMPTION` in querystring of the redirected URL, my guess is the Google Calendar API thinks our code is a malicious bot and is serving a captcha page.

Questions:
1. Has anyone else seen this?
2. Should there be an improvement to this library to tell google "don't serve a captcha page, we're a script, please instead give us an HTTP code"?
3. What are we getting "maximum redirect reached"? Seems like this library is doing something that's causing the Google API to continue redirecting?

**Comment by JustinBeckwith** [comment]
That feels ... wrong 🤣  Sorry y'all are running into this - sadly there's not a lot we're likely to be able to do with the library itself.  We're just calling the API endpoints the discovery service gives us, and follow redirects if we're given them.  

I suspect you're going to have a lot better luck filing a bug specifically with the Calendar API folks:
- https://developers.google.com/calendar/support
- https://issuetracker.google.com/issues/new?component=191627&template=824103

If it turns out there's something in the library we can do, please let us know!

**Comment by bradvogel** [comment]
For those following - this is a GCal API regression https://issuetracker.google.com/issues/159368649 that's been noticed by multiple companies.
