### ISSUE TITLE
analyticsReporting: filtersExpression with regex not working when escaping "?"

### ISSUE THREAD

**Issue by BoazKG93** [googleapis/google-api-nodejs-client#2312]
I'm facing a problem querying the analyticsReporting interface.

It seems that this package encodes already the filtersExpression automatically, but this causes an issue.
When I do:
`filtersExpression: "ga:pagePath=~\/testing\/test\?.*$"`

I get in my results also URLs that look like `/testing/test-wrong`

What I meant to do with this `\?` was to escape the question mark so i will get only URLs like `/testing/test?param=value`. Is there a way to escape this question mark with this package? There should be an option to turn off this automatic encoding.

Here is my whole code
```
      const res = await this.analyticsReporting.reports.batchGet({
        auth: this.client,
        requestBody: {
          reportRequests: [
            {
              viewId: process.env.ANALYTICS_VIEW_ID,
              dateRanges: [{ startDate: startDate, endDate: endDate }],
              metrics: [
                { expression: "ga:users" },
                { expression: "ga:avgTimeOnPage" },
                { expression: "ga:pageviews" },
              ],
              dimensions: [{ name: "ga:date" }, { name: "ga:pagePath" }],
              filtersExpression: `ga:pagePath=~\/public\/tour\/${slug}\?.*$`,
            },
          ],
        },
      });

```

What I'm getting is URLs like this:
```
/public/tour/slugValue
/public/tour/slugValue?
/public/tour/slugValue-and-some-other-stuff
```

When in fact I just want
```
/public/tour/slugValue?
```

**Comment by sofisl** [comment]
I've confirmed that this issue is reproducible. Also, I attempted to write the regex with URL-encoded values but that didn't seem to help. Internal bug b/178549778

**Comment by sofisl** [comment]
After further investigation, it seems that this has to do with how Javascript is interpreting the string. The backslash has a special meaning in a JavaScript string, so instead of escaping ? for the benefit of the upstream API we're escaping ? in the string.
In it's current configuration, '?' is being passed to the remote rather than '\?'. The simple fix is to put two slashes in front of any place in your query where you need to escape a character for the regex. So, to escape the ?, you should put \\? instead of \?.

An edit to your regex would be:

```
~\\/public\\/tour\\/${slug}\\?.*$
```
