### ISSUE TITLE
Please make method to get all public comments within a blog.

### ISSUE THREAD

**Issue by leestrument** [googleapis/google-api-nodejs-client#2333]
listByBlog seems for the owner of a blog. (I'm not sure, but it never work)
Please provide any method to get all public comments from other peoeple's blog.
Iterating each posts to get comments takes a lot of time.

**Comment by JustinBeckwith** [comment]
Greetings!  This repository is used to track issues related specifically to the `googleapis` npm module.  There isn't a lot we can do with the upstream Blogger API.  I suspect you'd have more luck posting in their help forum:
https://support.google.com/blogger/community/?hl=en&gpf=%23!forum%2Fblogger

If it turns out this is specifically a problem with this library - please do let us know!

**Comment by JustinBeckwith** [comment]
Greetings!  Does this API method do you what you're looking for?
https://developers.google.com/blogger/docs/3.0/reference/comments/list

Specifically, this method:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/blogger/v3.ts#L1703

**Comment by leestrument** [comment]
Thanks Justin.
Unfortunattely the "list" method doesn't give all comments.
It works only in selected post. I have to provide post id.
I want to get all comments from blogId at once.
The only way was listByBlog method, but it doesn't work. (on node.js, on their Doc site both)

**Comment by fhinkel** [comment]
Hi @sangdth , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Blogger API tag](https://stackoverflow.com/questions/tagged/google-blogger-api) is most appropriate for design and general troubleshooting.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
