### ISSUE TITLE
How to get Analytics data as timeseries or data table for charts?

### ISSUE THREAD

**Issue by BrunoQuaresma** [googleapis/google-api-nodejs-client#2351]
I have to read the number of users in a month but the API returns the consolidated number and I would like to know if it is possible to get the data by day to display it in a chart. I tried to find the API docs and samples without success.

**Comment by fhinkel** [comment]
Hi @BrunoQuaresma , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Analytics API tag](https://stackoverflow.com/questions/tagged/google-analytics-api) is most appropriate for design and general troubleshooting.
* [Google Analytics API's public issue tracker](https://developers.google.com/analytics/devguides/reporting/core/v4/help)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
