### ISSUE TITLE
Is Instance ID supported?

### ISSUE THREAD

**Issue by sm2017** [googleapis/google-api-nodejs-client#2402]
I searched a lot in documents , I cannot found Instance ID in documentation and sources
Is Instance ID supported?

https://developers.google.com/instance-id

**Comment by fhinkel** [comment]
Hi @sm2017 , thank you for opening the issue. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's google-api-nodejs-client tag](https://stackoverflow.com/questions/tagged/google-api-nodejs-client) is most appropriate for design and general troubleshooting.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
