### ISSUE TITLE
Type inconsistency in channel expiration

### ISSUE THREAD

**Issue by Sytten** [googleapis/google-api-nodejs-client#2405]
There is a type inconsistence in the channel `expiration` between the documentation and the library.
- In the library it is a `string`: https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/calendar/v3.ts#L326
- In the documentation it is a `long` (thus a `number` in JS): https://developers.google.com/calendar/v3/reference/calendarList/watch#response
- It is also a `number` in the example: https://developers.google.com/calendar/v3/push#example

It is also very confusing if we can send the `expiration` or we must send the `params.ttl` parameter. 
The documentation (https://developers.google.com/calendar/v3/reference/calendarList/watch#request-body) is contradicting the example (https://developers.google.com/calendar/v3/push#example). If this can be forwarded to the right team it would be greatly appreciated.

**Comment by JustinBeckwith** [comment]
Greetings!  On the type inconsistency - sadly, this is likely something we can't fix.  The types in this library are entirely generated from an underlying schema thingy, found here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/discovery/calendar-v3.json#L2012

That file is synchronized from here, where it maps to the actual underlying API:
https://calendar-json.googleapis.com/$discovery/rest?version=v3

So in a sense, we do what the magical JSON tells us to do :) Now in this case, the type is defined as a `string` because the underlying type is allowed to be a 64 bit integer.  Sadly, by default, JavaScript can only really represent 53 bit? integers natively:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

For the combination `expiration` and `params.ttl` issue - the best place to report that's going to the Google Calendar API issue tracker, where folks who know that product more closely are going to be able to help:
https://issuetracker.google.com/issues/new?component=191627&template=824103

Hope this helps!
