### ISSUE TITLE
Better ChangeLog

### ISSUE THREAD

**Issue by djmitche** [googleapis/google-api-nodejs-client#2438]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**

The ChangeLog for this library only says "This release has breaking changes".  That's not useful information.  What changed?  How?  What is the migration path?

Example: https://github.com/googleapis/google-api-nodejs-client/blob/master/CHANGELOG.md#6400-2020-11-05

 **Describe the solution you'd like**

A clear and concise description of what has changed in a major release.

 **Describe alternatives you've considered**

I realize that this package is autogenerated, and that these "has breaking changes" are per sub-component.  If there are changelogs for those subcomponents, please link to them in the changelog for this package.

**Comment by willbattel** [comment]
It is difficult for developers using this library to stay up to date, because every update requires us to dig unreasonably deep to figure out what has been changed, and if it breaks any of the APIs we're using. Listing the API changes on the Releases page would be a **_HUGE_** service to us.

This has been requested before ([here](https://github.com/googleapis/google-api-nodejs-client/pull/2096#issuecomment-628459223)), but unfortunately yielded no response.

**Comment by djmitche** [comment]
![image](https://user-images.githubusercontent.com/28673/103553351-55102f00-4e7b-11eb-98e7-044f74b45bbc.png)

This is definitely an improvement!

**Comment by bcoe** [comment]
We've had an improved CHANGELOG for quite some time now :tada: cleaning up some old issues.

**Comment by GauBen** [comment]
Hey! Sorry for waking up this issue, but the change log is no longer helful

![image](https://user-images.githubusercontent.com/48261497/231458373-fcbaa552-93e5-4669-94c1-ff458814097b.png)

**Comment by djmitche** [comment]
@GauBen I think you will be better-served opening a new issue and linking to this one.
