### ISSUE TITLE
JWT type not allowed for API client

### ISSUE THREAD

**Issue by employee451** [googleapis/google-api-nodejs-client#2451]
When generating an API client with this library, you cannot use JWT as the type for the auth parameter. This is needed when using service accounts.

By following [this documentation](https://developers.google.com/identity/protocols/oauth2/service-account), I have created a JWT using `google-auth-library`:

    import { JWT } from 'google-auth-library'

    const auth = new JWT({
        email: keys.client_email,
        key: keys.private_key,
        scopes,
    })

However, when creating an API client with `googleapis`, I get a type error saying that JWT is not allowed for the auth:

    const calendar = google.calendar({ version: 'v3', auth })

#### Environment details

  - OS: MacOS 10.15.7
  - Node.js version: v12.19.1
  - yarn version: 1.22.10
  - `googleapis` version: 59.0.0

Thanks!

**Comment by sofisl** [comment]
Hi @employee451,

Unfortunately I'm not able to reproduce this locally. Would you mind sharing your exact error?

A couple of other notes that *might* help you beforehand:

1. Is it possible for you to try using `google.auth.JWT()` to authenticate so that you're using the google-auth-library that is guaranteed to be type compatible with googleapis?

2. Also, can you update your version of googleapis to the latest?

**Comment by sofisl** [comment]
Hi @employee451, going to close this issue for now, feel free to reopen if this issue hasn't been resolved for you!
