### ISSUE TITLE
Sheets API type specification is wrong?

### ISSUE THREAD

**Issue by ivgtr** [googleapis/google-api-nodejs-client#2454]
I want to insert data into sheets using
 `google.sheets("v4").spreadsheets.values.append(params)`.
However, the `append(params)` type does not have a `resource` key that should be present to specify the data.
When I type `resource` and `typescript` it says it's an error!

I think this is a bug, but if it's not, I need your help.

#### Environment details
  - `googleapis` version:65.0.0

P.S.
If you specify a `resource`, an error appears, but execution shows that the operation is working properly.

**Comment by JustinBeckwith** [comment]
Greetings!  That would be because the API doesn't accept a `resource` property :) You can see an example of how this works here:
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/sheets/v4.ts#L5989

Is there a doc or something you're following that says to use `resource`?  That was an old property, which we renamed to `requestBody` a few years ago because of name conflict stuff.

**Comment by ivgtr** [comment]
Looks like I was referring to an old ref.
For me this was very useful, ty support @JustinBeckwith

**Comment by mcjcloud** [comment]
Is there an updated version of the sheets documentation? 

As of today I still see the the old `resource` property being used in the docs. https://developers.google.com/sheets/api/guides/values#appending_values. I'm looking at the "Node.js" tab for the code snippets.
