### ISSUE TITLE
Allow GoogleAuth.keyFile to accept file content

### ISSUE THREAD

**Issue by Akxe** [googleapis/google-api-nodejs-client#2466]
Currently one of two simples method is this:

```ts
new google.auth.GoogleAuth({
	keyFile: '../../assets/secrets/google.json',
	scopes: [
		'https://www.googleapis.com/auth/gmail.send',
		'https://www.googleapis.com/auth/gmail.readonly',
	],
});
```

 **Is your feature request related to a problem? Please describe.**
The snippet above may break if typescript compiles the code to a `dist` folder. Since the file contents are not linked via an import, typescripts missed the `.json` file.

 **Describe the solution you'd like**
I would propose 2 solutions:
1. `GoogleAuthOptions.keyFile` would newly accept `Object`, the result of importing `keys.json` file, or `string` with content of `keys.pem`, or `keys.p12`.

 **Describe alternatives you've considered**
Make sure, the `.json` file will be moved to the dist folder too.

 **Additional context**
Since the `GoogleAuthOptions` has the property `keyFilename` and `keyFile`, it almost leads to the belief, that `keyFile` should have been always accepting file contents rather than the path to it.

**Comment by sofisl** [comment]
Hi @Akxe,

From your suggestion, it sounds like there might be a confusion regarding the naming.

I'm curious though, have you looked at the `credentials` property in the GoogleAuth constructor? It might be accomplishing what you're looking to do:

```
export interface GoogleAuthOptions {
  /**
   * Path to a .json, .pem, or .p12 key file
   */
  keyFilename?: string;

  /**
   * Path to a .json, .pem, or .p12 key file
   */
  keyFile?: string;

  /**
   * Object containing client_email and private_key properties
   */
  credentials?: CredentialBody;

  /**
   * Options object passed to the constructor of the client
   */
  clientOptions?: JWTOptions | OAuth2ClientOptions | UserRefreshClientOptions;

  /**
   * Required scopes for the desired API request
   */
  scopes?: string | string[];

  /**
   * Your project ID.
   */
  projectId?: string;
}
```

I am going to close this for now as I'm hoping this answers your question, but also because this is better addressed in our [googleapis/google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs) repository. If this answer isn't satisfactory, feel free to reopen this bug there. Thanks!
