### ISSUE TITLE
Books Node.js API samples

### ISSUE THREAD

**Issue by rmgreenstreet** [googleapis/google-api-nodejs-client#2507]
It would be great to have samples of how to use the `googleapis.books` Node.js API, especially for searching. I've seen the main API documentation and I believe right now my only option is to construct my own query URIs myself, without more explicit instructions of how to use this API

**Comment by sofisl** [comment]
Hi @rmgreenstreet, there are samples in the comments of the api source [code](https://github.com/googleapis/google-api-nodejs-client/blob/a6f3e79b2123a0579e341ce08263edef5aef50e3/src/apis/books/v1.ts#L1230). I hope these samples help, otherwise feel free to post a more specific question about the API!
