### ISSUE TITLE
encodeURIComponent all url parameters

### ISSUE THREAD

**Issue by ryanseys** [googleapis/google-api-nodejs-client#275]
A developer ran into an issue (#268) and the fix was to url encode his parameters. We should be doing this by default for URL parameters that will end up in the url.

**Comment by ssorallen** [comment]
The introduction of URI encoding made sense to me, and we happened to be using a version of this library where it was included. The auto-encoding was reverted in commit https://github.com/google/google-api-nodejs-client/commit/fbcb962a51a0f4e420fab1c3be9a356709fb7c14#diff-9475ffcd397ad130248cf92c9a813d65 with no explanation though. Is it intentional that this library expects the user to `encodeURIComponent` parameters before passing them?

My issue is similar to @Quentin01: a calendar with a hash in it like `"fr.french#holiday@group.v.calendar.google.com"` constructs an invalid URL. Something like the following:

```
googleapis.calendar.client(/* params */).events.list({
    calendarId: 'fr.french#holiday@group.v.calendar.google.com'
});
```

attempts to load the following URL:

    https://content.googleapis.com/calendar/v3/calendars/fr.french#holiday@group.v.calendar.google.com/events

Since a `#` is a reserved character, the `googleapis` client returns a 404 after attempting to load only `https://content.googleapis.com/calendar/v3/calendars/fr.french`.
