### ISSUE TITLE
Tutorial - fails to import json keys

### ISSUE THREAD

**Issue by bandwiches** [googleapis/google-api-nodejs-client#3037]
Fairly new to NodeJS, so forgive me if this is not a big deal.  But, this line below was reading my json credential file and returning `undefined` for all the keys.  I removed `.web` from the line below and that fixed it.  Not sure why, but hope this helps anyone in the future with the same issue.

https://github.com/googleapis/google-api-nodejs-client/blob/0a9f52cf81120992b15634a2786ddb53e1e6167e/samples/oauth2.js#L32

**Comment by sofisl** [comment]
Hi @bandwiches, thanks for opening this issue. This occurs because there are different types of oauth2 keys, namely:
<img width="629" alt="Screen Shot 2022-08-18 at 12 45 44 PM" src="https://user-images.githubusercontent.com/55454395/185481554-d88c133b-fb2d-4156-b1e9-03541c88af5f.png">

We tested a few, and some of the have an `installed property`:

```
{"installed":{"client_id":"xxxxxx"}}
```

Others (including web apps), have a `web` property:

```
{"web":{"client_id":"xxxxxx"}}
```

The tutorial expects you're creating credentials for a web application, but you can confirm which property you need by opening the JSON you downloaded.

Hope this helps!

**Comment by bandwiches** [comment]
That makes sense, thanks for the explanation!
