### ISSUE TITLE
Google Drive API Missing Resource Field Within v3 Definition

### ISSUE THREAD

**Issue by matthewzhaocc** [googleapis/google-api-nodejs-client#3080]
#### Environment details

  - OS: MacOS 12.6
  - Node.js version: 14.17.2
  - npm version: 6.14.15
  - `googleapis` version: 105.0.0

#### Steps to reproduce

If you create a file following the [docs](https://developers.google.com/drive/api/guides/manage-uploads), client.files.create does not have a resource field according to the googleapis source code [here](https://github.com/googleapis/google-api-nodejs-client/blob/main/src/apis/drive/v3.ts#L6541) when the documentation says there is a resource field.

**Comment by sofisl** [comment]
Blocked by #3085

**Comment by sofisl** [comment]
Still need to publish library, will do on 13th.

**Comment by officialabdulrehman** [comment]
@sofisl any ETA on this ?

**Comment by samiam376** [comment]
any update here?

**Comment by speyso-support** [comment]
@sofisl Is there any update on this? How do I create a folder or give my file a name without it?

**Comment by sofisl** [comment]
Hi @matthewzhaocc and @speyso-support, the library has since been updated, but I think where you would set the name of the file is in the `requestBody`, here: https://github.com/googleapis/google-api-nodejs-client/blob/3a4972db99998789a6b514eb4eebe490626a39d4/src/apis/drive/v3.ts#L707

I've confirmed this works on my end; if you can confirm it works for you, then I will create an issue on [this repo](https://github.com/googleworkspace/node-samples/blob/main/drive/snippets/drive_v3/file_snippets/upload_basic.js) for the documentation.

**Comment by sofisl** [comment]
Closing this for now; feel free to reopen if this solution doesn't work for you.
