### ISSUE TITLE
Method should handle stream errors

### ISSUE THREAD

**Issue by bradvogel** [googleapis/google-api-nodejs-client#432]
If I'm passing a stream to a google library function, and that stream emits an error, shouldn't the library handle that and treat it as a failure?

```js
googleclient.users.messages.insert({
  userId: 'me',
  media: {
    mimeType: 'message/rfc822',
    body: bodyStream // bodyStream emits an error
  }
}, callback);
```
I know that I can catch it outside using `bodyStream.on('error', ...)`, but since the library is receiving the stream, shouldn't it handle?

**Comment by wearhere** [comment]
> since the library is receiving the stream

I would say, since the library is _reading_ the stream—that is what causes it to emit the error.

**Comment by JustinBeckwith** [comment]
Funny enough, this is still a bug.  The bug is in axios, and will need to be fixed there.  I submitted a PR here:
https://github.com/axios/axios/pull/1425

**Comment by kinwa91** [comment]
@JustinBeckwith is this fixed? :)

**Comment by sduskis** [comment]
@JustinBeckwith is this fixed? :)

**Comment by JustinBeckwith** [comment]
@JustinBeckwith is this fixed?

**Comment by bradvogel** [comment]
@JustinBeckwith is this fixed? :)

**Comment by JustinBeckwith** [comment]
After taking a really long look at this - I starting to think that it's not actually possible 😆 The issue is that the errors raised from the stream are happening in a different context than the request.  For example:

```js
async function doStuff() {
  const reader = new stream.Readable();
  reader.on('error', e => {
    throw e;
  });
}
doStuff().catch(console.error);
```

The `throw` that happens here is outside of the context of the async function, so even wrapping this in a `try/catch` isn't going to capture the error.  

It's possible that I've been staring at this for too long, so I am going to + in @ofrobots and @stephenplusplus just to make sure I'm not crazy.
