### ISSUE TITLE
Google Sheets API v4 for addChartRequest doesn't work properly

### ISSUE THREAD

**Issue by AharonDror** [googleapis/google-api-nodejs-client#728]
I've followed the documentation for adding chart.
For example:
```js
addChart: {
  chart: {
    chartId: someId,
    spec: {
      basicChart: {
        chartType: 'LINE',
        legendPosition: 'NO_LEGEND',
        axis: [
          {
            position: 'LEFT_AXIS',
            title: 'someTitle',
            format: {
              fontSize: 30,
              foreGroundColor: {
                red: 1,
                green: 0,
                blue: 0,
                alpha: 0.5
              },
              italic: true,
              strikethrough: true
            }
          },
          {
            position: 'BOTTOM_AXIS'
          }
        ]
      }
    }
  }
}
```

I see some weird behavior
One issue is that I have no control over the actual color of the Axis. Modifying the 'foreGroundColor' has no effect, and the resulting axis title has a black color regardless.

'strikeThrough' has no effect, and 'italic' has weird behavior: when specified to either true or false then the title doesn't have italics, but when omitted then the title has italics.

**Comment by JustinBeckwith** [comment]
Comically, I also can't get this to work through the API explorer.  I keep getting 500s 🤷‍♂️ 
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/batchUpdate

A few things I did observe in your snippet though:
- The `red`, `blue`, and `green` fields are valued 0-255.  If you want red - try setting red to `255` instead of 1 :)
- You have `foreGroundColor` - the property name has a lower g, `foregroundColor`

These are just the first I'm noticing :)  

@grant  - do we have a simple working REST API sample of `addChart` lying around anywhere?  I'm hopelessly flailing trying to get this to work.

**Comment by grant** [comment]
We don't have an `addChart` sample right now in any programming language.

@AharonDror Can you file a bug report here so the API maintainers are aware of this issue?
https://issuetracker.google.com/issues/new?component=191608&template=823917

The best doc we have on charts is here:
https://developers.google.com/sheets/api/samples/charts

**Comment by grant** [comment]
@JustinBeckwith We can probably close this issue. We've given a couple suggestions.
